// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qvjoldaphzuvlxbrptiq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF2am9sZGFwaHp1dmx4YnJwdGlxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwMjA0NTUsImV4cCI6MjA2MzU5NjQ1NX0.0aGoKVdOqBZsc4i_oaG61kPwj9lOzlIf_P642yehXKo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);